### ISSUE TITLE
Collaborating with tests

### ISSUE THREAD

**Issue by Matiusco** [gumdropsteve/tweet-your-tweet#1]
I'm getting in touch with your work right now. I do not know much about python, but I'll try to help run tests and try to solve problems if I can. Let me know where you need me to have a more specific look. Sorry for my poor English. My first language is Portuguese.

**Comment by gumdropsteve** [comment]
Hey @Matiusco - apologies for the delayed response. 

I saw the notification in email a while ago but did not realize you had raised 2 issues. I will check back each day from now on. Thank you for your patience and interest in the repo! 

No need to apologize for your English; if I can't understand what you're saying, or can't get my idea across in English that you can understand, it is just as bad a reflection on my English - haha!  

I commented back on your issue #2 looking for a bit more clarification. It sounds like an interesting feature to add. Let me know when you get the chance. Thanks.

**Comment by gumdropsteve** [comment]
Going to close this issue as introductions have been made. 

Let's continue the conversation in #2 . Looking forward to seeing what we can get done. Thanks.
